server:
  port: 8090
spring:
  application:
    name: mq-producer
  cloud:
    stream:
      bindings:
        # 定义 name 为 output 的 binding 生产
        backtracking-out-0:
          content-type: application/json
          destination: test-topic3
        transaction-out-0:
          content-type: application/json
          destination: TransactionTopic
      rocketmq:
        binder:
          name-server: 192.168.101.44:9876;192.168.101.45:9876
        bindings:
          backtracking-out-0:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              group: backtracking-producer-group # 生产者分组
              sync: true # 是否同步发送消息，默认为 false 异步。
          transaction-out-0:
            # 对应 RocketMQProducerProperties类
            producer:
              transactional: true
              group: transaction-producer-group
              sync: true